### ISSUE TITLE
Wrong PIXm IG version mentionned in ITI-83/104

### ISSUE THREAD

**Issue by msmock** [ehealthsuisse/ch-epr-mhealth#103]
The link to the PIXm profile leads to the latest version, while the label specifies v3.0.0.

**Comment by msmock** [comment]
Original feedback from Quentin, but can't find the reference. Can you give me a hint where to look?

**Comment by qligier** [comment]
From the text, I think it appears in https://build.fhir.org/ig/ehealthsuisse/ch-epr-mhealth/iti-83.html.
Sorry, I initially filled it in the wrong issue it seems.

**Comment by qligier** [comment]
The link points to the latest version (v3.0.3), the label says v3.0.0 and [we import v3.0.2 in the IG](https://github.com/ehealthsuisse/ch-epr-mhealth/blob/master/input/ch.fhir.ig.ch-epr-mhealth.xml#L54-L56), it is quite confusing.

**Comment by oliveregger** [comment]
we should update pixm to 3.0.3
pdqm -> 2.4.0 (ci build 2.4.0), text has to be fixed, remove pixm reference
mhd -> 4.2.1. (ci-build 4.2.0)
