### ISSUE TITLE
Patient relationships

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-epr-mhealth#119]
In http://fhir.ch/ig/ch-epr-mhealth/StructureDefinition-ch-pixm-patient.html

`Patient.contact.relationship` is allowed (and required within `contact`).

Amendment 1 of Annex 5 EPRO-FDHA says, for PIXv3 Feed: (§1.7.1.1, p34)

> PersonalRelationship
code [1..1] (M) Role (CE)
{CWE:PersonalRelationshipRoleType}
MUST NOT be used.

And for PDQv3 response (§1.9.2.1, p38):

> PersonalRelationship
code [1..1] (M) Role (CE)
{CWE:PersonalRelationshipRoleType}
Codes: FTH=Father 
MTH=Mother

Originally reported in #73

TODO @oliveregger : Create a Change Proposal that code [1..1] (M) Role (CE) {CWE:PersonalRelationshipRoleType} is changed to No further refinement (or harmonized with Query where MTH and FTH is used).

**Comment by oliveregger** [comment]
Change proposal submitted on Feb 1, 2024:

Change Proposal that code [1..1] (M) Role (CE) {CWE:PersonalRelationshipRoleType} in PIXv3 Feed is
harmonized with Query where MTH and FTH is used (add MTH
and FTH for PersonalRelationshipRoleType to PIXv3 Feed).
