### ISSUE TITLE
Message Semantics

### ISSUE THREAD

**Issue by msmock** [ehealthsuisse/ch-epr-mhealth#135]
Some parts of messages are described in section 3.1.4 "Messages", other parts -- in section 3.1.6 "Message Semantics". Would it make sense to combine these sections?

**Comment by qligier** [comment]
Yes, I am editing the transaction pages to match more closely the usual structure of IHE profiles as part of #129

**Comment by msmock** [comment]
Does not apply to ITI-71. No work for me.
