### ISSUE TITLE
Introduction enhancements

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-epr-mhealth#140]
What is the difference between 'Client authentication' and 'User Authentication'?

A reference to other MHD-like (FHIR/REST) transactions could be added. It seems like this profile is the main one for mobile transactions in the EPR (as its name implies), but it is not. A description could be added to explain that other transactions are described in e.g. PPQm, ATC.

_Originally reported in #76_

**Comment by martinsmock** [comment]
The difference between 'Client authentication' and 'User Authentication' is as described in the IUA Trial Implementation: 
- In "User Authentication" the natural person identifies and authenticates using an Identity Provider with the authenticators registered for the natural person. 
- In "Client Authentication" the client application authenticates, such that the environment knows which application the natural person used when performing a request. Typical authenticators are client_id and client-secret, signed messages or X.509 certificates on the TLS level (which in fact identifies the network node, but not the application).

**Comment by oliveregger** [comment]
2nd part: ppqm is planned to be integrated

**Comment by oliveregger** [comment]
add to the scope of precisins in 1.2.2 on the bottom:

The FHIR API to read audit trail consumption requirements is defined in a separate national Integration Profile (SR816.11, Annex 5, Extension 2) with the supporting [Implementation Guide](https://fhir.ch/ig/ch-atc/index.html).

**Comment by msmock** [comment]
Clarified the introduction with client authentication /authorization and  user authentication/authorization
