### ISSUE TITLE
enforce trace context in http header

### ISSUE THREAD

**Issue by martinsmock** [ehealthsuisse/ch-epr-mhealth#143]
Add requirement to use the trace context as defined in W3C standard (https://www.w3.org/TR/trace-context/) for all transactions,

**Comment by oliveregger** [comment]
daniel will work on a proposal including also the mapping to soap:header

for FHIR transations we need to include it for each transaction where appropriate in 
- referenced standards
- Message Semantics

**Comment by oliveregger** [comment]
indepent of daniel's work, we can integrate it

**Comment by qligier** [comment]
Do we describe now requirements to add the trace identifier to the audit events? It should be described here, and probably in CH:ATC in the future.

**Comment by oliveregger** [comment]
- we should mention it for sure how to add it to the FHIR AuditEvent resources in the IG
- for the DICOM AuditEvent Message this needs to be described in the Annex
- CH ATC should be in a future version also have that field enabled

**Comment by qligier** [comment]
BALP supports the X-Request-Id header, but not sure if it's the best mapping for traceparent too: https://chat.fhir.org/#narrow/stream/179223-ihe/topic/Specify.20tracing.20identifiers.20in.20AuditEvents.20.28BALP.29/near/419788189

https://profiles.ihe.net/ITI/BALP/content.html#35731-x-request-id-header

**Comment by qligier** [comment]
Issue raised in BALP: https://github.com/IHE/ITI.BasicAudit/issues/94
See also: https://chat.fhir.org/#narrow/stream/179247-Security-and.20Privacy/topic/TraceID's
FHIR documentation with trace IDs: http://build.fhir.org/audit-event-example-create-traceID.html

**Comment by qligier** [comment]
> Issue raised in BALP: https://github.com/IHE/ITI.BasicAudit/issues/94

Create a PR for the two new headers
