### ISSUE TITLE
IUA: Text correction

### ISSUE THREAD

**Issue by martinsmock** [ehealthsuisse/ch-epr-mhealth#144]
Correct: 

1. For SMART on FHIR Apps is launched as EHR Launch, ... SHOULD read For SMART on FHIR Apps is launched as EHR Launch, 
2. In "https://build.fhir.org/ig/ehealthsuisse/ch-epr-mhealth/iti-iua.html#security-consideration" remove: ​"The IUA Authorization Server SHALL enforce authentication of the user by redirecting the App to the User Authentication Provider (Identity Provider) as described in [IUA](https://build.fhir.org/ig/ehealthsuisse/ch-epr-mhealth/iti-71.html#expected-actions-iua-authorization-server)."

**Comment by msmock** [comment]
Fixed in master branch
