### ISSUE TITLE
IUA changes after IHE ITI CP call

### ISSUE THREAD

**Issue by oliveregger** [ehealthsuisse/ch-epr-mhealth#152]
1. Access token format ValueSet is different 
2. Access token format as Array (text and example)
3. Removal of the redirect_uri of the IUA paramter
4. link to full-url iua https://profiles.ihe.net/ITI/IUA/index.html#372-incorporate-access-token-iti-72 instead of iti-72.html (see qa.html)

**Comment by msmock** [comment]
Done
