### ISSUE TITLE
IUA handling of client authentication

### ISSUE THREAD

**Issue by oliveregger** [ehealthsuisse/ch-epr-mhealth#19]
How is client authentication is handled with the Authorization Server? Should the token_endpoint_auth_methods be further defined?

**Comment by oliveregger** [comment]
see 3.103.4.2.2 Message Semantics, https://profiles.ihe.net/ITI/IUA/index.html

**Comment by oliveregger** [comment]
same client authentication method as for next version of annex 8 will be proposed (open id connect fixes that)

**Comment by msmock** [comment]
Clients shall be authenticated against the Identity Provider via a digital signature of the request token. The clients shall not be authenticated explicitly in the IUA Authorization Server, only implicitly via the IdP token of the authenticated user session. Thus technical user are currently not allowed in IUA.
