### ISSUE TITLE
MHD [ITI-67] Find Document References Response validator shall be validating a Bundle instead of a Document Manifest

### ISSUE THREAD

**Issue by NBailliet** [ehealthsuisse/ch-epr-mhealth#3]
We do not currently have a dedicated structure definition for the response of the ITI-67 transaction Find Document References.
We changed the validator temporarily which is now using a Bundle structure definition from the IG FHIR Server instead of the initially configured Document Reference structure definition.

Link to the Gazelle JIRA ticket : https://gazelle.ihe.net/jira/browse/EHS-455

**Comment by oliveregger** [comment]
a constraint should be added that to satisfy the requirements when the fullUrl is specified in a document bundle:
URI for resource (Absolute URL server address or URI for UUID/OID)

```
Except for transactions and batches, each entry in a Bundle must have a fullUrl which is the identity of the resource in the entry. Note that this is not a versioned reference to the resource, but its identity. Where a resource is not assigned a persistent identity that can be used in the Bundle, a UUID should be used (urn:uuid:...).
```
see also related issue from projecathon: https://gazelle.ihe.net/jira/browse/EHS-443

**Comment by ziegm** [comment]
Issues resolved with following commits:
- [Bundle instead of DocumentManifest](https://github.com/ehealthsuisse/ch-epr-mhealth/commit/862d606209a32bf19bedcb403bd03ae270eb2226)
- [fullUrl](https://github.com/ehealthsuisse/ch-epr-mhealth/commit/5d8d6c98899c6b329b44e624e572aabdda5882d7)
