### ISSUE TITLE
PIXm Patient Identifier Cross-reference Manager (server) - JSON Representation (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-mhealth#30]
ch.fhir.ig.ch-epr-mhealth#0.2.0 /CapabilityStatement-CH.PIXm.Manager.json.html

The CapabilityStatement does not include the feed capabilities. Depending on the future development of the PIXm Feed this should be incorporated.

Oliver Egger, ahdis ag

**Comment by oliveregger** [comment]
solved with integrated PR
