### ISSUE TITLE
Record Audit Event [ITI-20] (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-mhealth#38]
ch.fhir.ig.ch-epr-mhealth#0.2.0 /iti-20.html

There are no AuditEvent examples defined for the transactions.

Oliver Egger, ahdis ag

**Comment by oliveregger** [comment]
- The IHE MHD and PIXm base IG's have added now examples.
- There is a [ITI.BasicAudit](http://build.fhir.org/ig/IHE/ITI.BasicAudit/branches/main/content.html#35741-saml) in development which describes how to map between XUA/IUA to the AuditEvent resource
