### ISSUE TITLE
RESTful ATNA not shown in sequence diagrams (Marco Studer, Cistec AG)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-mhealth#46]
ch.fhir.ig.ch-epr-mhealth#1.1.0 /iti-restful-atna.html

Chapter 2.4.6 (Process Flow) relates to the sequence diagrams, but these diagrams don't contain any additional information regarding ATNA. The link should be either removed / replaced or the diagrams might be extended to explain which transactions required ATNA logs. 

Marco Studer, Cistec AG

**Comment by oliveregger** [comment]
need to adapt the wording.

**Comment by oliveregger** [comment]
Remove the chapter Process Flow, the chapter UseCase with reference to ATNA, ATNA supplement already describe the necessary Process flow.
