### ISSUE TITLE
CH MHD SubmissionSet Comprehensive (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-mhealth#47]
ch.fhir.ig.ch-epr-mhealth#1.1.0 /StructureDefinition-ch-mhd-submissionset-comprehensive.html

List.identifier mentions: identifier, for entryUUID set use to offical, however the narrative text of MHD does not allow entryUUID and this will be corrected in the next MHD version (after 4.1.0). Text should be adapted for next version.

Oliver Egger, ahdis ag

**Comment by oliveregger** [comment]
update to newest published MHD version and remove entryUUID requirements

**Comment by ziegm** [comment]
10.11.2022: not adapted yet -> https://build.fhir.org/ig/IHE/ITI.MHD/StructureDefinition-IHE.MHD.UnContained.Comprehensive.SubmissionSet.html
