### ISSUE TITLE
No entryUUID values for publication (iti-65) (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-mhealth#50]
ch.fhir.ig.ch-epr-mhealth#1.1.0 /Bundle-2-7-BundleProvideDocument.json.html

We have entryUUID in our example, but according to MHD they should not be added by the Document Source (need to be added by the DocumentResponder):

https://build.fhir.org/ig/IHE/ITI.MHD/ITI-65.html

>Except that the Document Source shall not provide any entryUUID values.

Oliver Egger, ahdis ag

**Comment by oliveregger** [comment]
related to #47
