### ISSUE TITLE
Various typos

### ISSUE THREAD

**Issue by heg2** [ehealthsuisse/ch-epr-mhealth#51]
There are some typos that should be corrected:
- in 2.2.1: "...the initial demographics data can be feeded to the MPI" - "fed" instead of "feeded"
- in 2.2.4: "Option" should be lower case here
- 3. Transactions: The link to “Mobile Patient Identifier Cross-reference Query [ITI-83] [ITI-83]” has the [ITI-83] twice
- Missing “.” at end of paragraph 3.1
- in the sequence diagram 4.5.1, "Authorization Token" (in [05] and [09]) and "code" (in [11]) are used for the same thing? same in 4.5.3 [16], [20] and [21]
- Typos in Sequence Diagram 4.5.3 “Auth*z* Server”, “standalone launc*e* sequence” (in [04])

**Comment by ziegm** [comment]
The typos listed above are corrected.

@oliveregger 
This item is still open:
_in the sequence diagram 4.5.1, "Authorization Token" (in [05] and [09]) and "code" (in [11]) are used for the same thing? same in 4.5.3 [16], [20] and [21]_
How should it be resolved?
