### ISSUE TITLE
use another accronym for ig instead of mhealth

### ISSUE THREAD

**Issue by oliveregger** [ehealthsuisse/ch-epr-mhealth#64]
telco 25.6, mhealth associates "mobile", however this implementation guide is not only for mobile applications,
but offering a RESTFul API to the Swiss EPR. This focus should be adjusted:

proposed new names, candidates?

- CH EPR FHIR 
- CH EPR REST
- CH EPR mIHE

**Comment by oliveregger** [comment]
focus of profile should be for easier implementation for primary systems

**Comment by oliveregger** [comment]
can we use CH EPR FHIR?

**Comment by qligier** [comment]
Fixed with #159.
