### ISSUE TITLE
Sequence Diagrams - patient get document – generic mHealth option - local ID? (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-mhealth#69]
ch.fhir.ig.ch-epr-mhealth#3.0.0-ballot /sequencediagrams.html

Step 11 mentions: query MPI_A-PID from MPI using local ID and access token

How does the App know what the ""local ID"" of the patient is?

From the IUA Basic Token the user_id is returned (see http://fhir.ch/ig/ch-epr-mhealth/iti-71.html), however there is currently no API defined how to correlate the user_id to a ""local ID or MPI-PID"".

A clarification of the sequence diagram would be helpful.

Oliver Egger, ahdis

**Comment by oliveregger** [comment]
In the new setup, the Patient Portal would do the mapping and would know to map the userid to the 
localId

**Comment by oliveregger** [comment]
MS: the launching portal has to provide all the information the app requires, and that may contain more than one id of the patient
