### ISSUE TITLE
Comments on ITI-103

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-epr-mhealth#71]
http://fhir.ch/ig/ch-epr-mhealth/iti-103.html:

The access_token_format are described as “ihe_jwt” and “ihe_saml”, but IUA actually uses "ihe-jwt" and "ihe-saml".

The SMART on FHIR URL construction is required (`.well-known/smart-configuration`)? If so, it should be specified.

`grant_types_supported`: It is described as "SHALL be authorization_code", but the example shows `["client_credentials", "authorization_code", "id_token", "refresh_token", "urn:ietf:params:oauth:grant-type:jwt-bearer"]`. Should it be "SHALL include authorization_code"?
Edit: In ITI-71, only authorization_code is allowed. So it seems the message example is wrong.

`token_endpoint_auth_methods`: IUA specifies "When provided, this list shall include client_secret_basic", this statement could be copied.

In the message example, I'm unsure "code id_token" is a true `response_types_supported`.

The link to the IUA profile leads to the v2.2, while the label specifies v2.1.
The link to the SMART APP Launch profile leads to the v2.1.0, while the label specifies v1.0.0.

~Typo: _SHALL response with_ → _SHALL respond with_~ <ins>tracked in #106</ins>

**Comment by msmock** [comment]
Fixed: The access_token_format are described as “ihe_jwt” and “ihe_saml”, but IUA actually uses "ihe-jwt" and "ihe-saml" and changed to "ihe-jwt"

**Comment by msmock** [comment]
Changed the summary issue to individual issues.
