### ISSUE TITLE
Comments on PIXm/PDQm

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-epr-mhealth#73]
~No Patient profile and no mapping with PIXv3/PDQv3?~ <ins>fixed by #115</ins>

## http://fhir.ch/ig/ch-epr-mhealth/iti-104.html
~All links to the PIXm profile lead to the latest version, while the label specifies v3.0.0.~ <ins>won't fix</ins>

~Typo: _SHALL be conform to the PIXm_ → be conformed, or conform~ <ins>tracked in #106</ins>

~_The EPR-SPID as an identifier MAY be added_: In Annex 5 §1.7.1.1, the EPR-SPID SHALL be conveyed.~ <ins>tracked in #111</ins>

~_Resolve Duplicate Patient_: is it really allowed to clients? It seems an operation for administrators only, because that would change access to the discarded patient.~ <ins>allowed, no change needed</ins>

~_Add Patient_: is it really allowed to clients? It was supported in PIXv3, but seems weird nonetheless.~ <ins>allowed, no change needed</ins>

## http://fhir.ch/ig/ch-epr-mhealth/iti-78.html
~The link URL and label to the IHE PDQm profile are wrong.~ <ins>fixed in 7496ff7</ins>

~The link to FHIR leads to R5.~ <ins>fixed in 9ba6757</ins>

~_The message semantics is the same as defined in [2:3.78.4.1.2](https://profiles.ihe.net/ITI/PDQm/ITI-78.html#2378412-message-semantics)_: In Annex 5 §1.9.1.1: _The PatientTelecom Query Parameter MUST NOT be used_. Why is it allowed here?~ <ins>tracked in #117</ins>

~_If there are more than 5 matches, the result should return zero matches._: An OperationOutcome should be required in that case, with the details provided in the XDS counterpart.~ <ins>tracked in #80</ins>

## http://fhir.ch/ig/ch-epr-mhealth/iti-83.html
~The link to FHIR leads to R5.~ <ins>fixed in 9ba6757</ins>

~_targetSystem: SHALL be Restricted to the Assigning authority of the community and/or the EPR-SPID._: In Annex 5 §1.8.1.1: _The DataSource Parameter SHALL be specified to the assigning authorities of the EPR-SPID and the MPI-PID in the affinity domain._ The 'or' is not allowed in PIXv3.~ <ins>tracked in #112</ins>

## http://fhir.ch/ig/ch-epr-mhealth/StructureDefinition-ch-pixm-patient.html
~`Patient.contact.relationship` is allowed (and required). In Annex 5 §1.7.1.1, `PersonalRelationship.code` must not be used.~ <ins>tracked in #119</ins>

## http://fhir.ch/ig/ch-epr-mhealth/StructureDefinition-ch-pixm-provider-organization.html
~Typo: _The value shall be expressed as and ISO OID_ → as an ISO OID~ <ins>tracked in #106</ins>

**Comment by oliveregger** [comment]
104:
___

>Typo: SHALL be conform to the PIXm → be conformed, or conform
SHALL conform to PIXm

https://fhir.ch/ig/ch-epr-mhealth/iti-104.html#:~:text=If%20the%20patient%20is%20already%20registered%20in%20a%20community%2C%20the%20MPI%2DPID%20SHALL%20be%20provided%20as%20an%20identifier.%20The%20EPR%2DSPID%20as%20an%20identifier%20MAY%20be%20added.

Change text to: SHALL convey the patient’s local ID and the EPR-SPID.

>https://fhir.ch/ig/ch-epr-mhealth/StructureDefinition-ch-pixm-patient.html
EPR-SPID min cardinality should be 1
and Identifier cardinalty should be 2 (except we would map additional identifieres to otherIdenttifiers in PIXv3)

Resolve Duplicate Patient/Add Patient: both are allowed sending the messages what happened in the local system.

**Comment by oliveregger** [comment]
78:
>The link URL and label to the IHE PDQm profile are wrong.
fix PQD in link: https://profiles.ihe.net/ITI/PQDm/index.html
link to the correct version

>The link to FHIR leads to R5.
adjust link to r4 for every occurence

>The message semantics is the same as defined in [2:3.78.4.1.2](https://profiles.ihe.net/ITI/PDQm/ITI-78.html#2378412-message-semantics): In Annex 5 §1.9.1.1: The PatientTelecom Query Parameter MUST NOT be used. Why is it allowed here?

need to add the sentence too for ITI-78 and split request reponse message semantics (or within the text)

>If there are more than 5 matches, the result should return zero matches.: 
covered in https://github.com/ehealthsuisse/ch-epr-mhealth/issues/80

**Comment by oliveregger** [comment]
>Patient.contact.relationship is allowed (and required). In Annex 5 §1.7.1.1, PersonalRelationship.code must not be used.

@msmock  PersonalRelationship.code must not be used in the feed, but we are able to query it with FTH and MTH (1.9 Requirements on PDQV3 for Patient Demographics Query). does this make sense?

**Comment by oliveregger** [comment]
>Typo: The value shall be expressed as and ISO OID → as an ISO OID
fix typo

**Comment by oliveregger** [comment]
TODO Oliver: Create a Change Proposal that code [1..1] (M) Role (CE) {CWE:PersonalRelationshipRoleType} is changed to No further refinement (or harmonized with Query where MTH and FTH is used).

**Comment by qligier** [comment]
The issue has been split.
