### ISSUE TITLE
Comments on RESTful ATNA

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-epr-mhealth#74]
## http://fhir.ch/ig/ch-epr-mhealth/iti-restful-atna.html
~No link to ITI-20 or ITI-81.~ <ins>invalid</ins>

## http://fhir.ch/ig/ch-epr-mhealth/iti-20.html
~The link to the IHE profile leads to v3.4.~ <ins>won't fix</ins>

~The link to FHIR leads to R5.~ <ins>fixed in 9ba6757</ins>

~The CapabilityStatements are missing.~ <ins>tracked in #107</ins>

## http://fhir.ch/ig/ch-epr-mhealth/AuditEvent-ex-auditProvideBundle-source.json.html
~`source.site`: Why is it URN-encoded? It is not URN-encoded in `AuditEnterpriseSiteID`, and `site` is not an Identifier.~ <ins>tracked in #108</ins>

**Comment by oliveregger** [comment]
>No link to ITI-20 or ITI-81.
link to the profile pdf is there

>http://fhir.ch/ig/ch-epr-mhealth/iti-20.html
fix links and add a cap statements

> http://fhir.ch/ig/ch-epr-mhealth/AuditEvent-ex-auditProvideBundle-source.json.html
the  urn:oid prefix can be removed

**Comment by qligier** [comment]
The issue has been split to better track changes.
