### ISSUE TITLE
Comments on MHD

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-epr-mhealth#75]
## For the 4 transactions
~The links to the MHD profile lead to v4.2.1~ <ins>won't fix</ins>

~The link to FHIR leads to R5.~ <ins>fixed in 9ba6757</ins>

## http://fhir.ch/ig/ch-epr-mhealth/StructureDefinition-ch-mhd-providedocumentbundle-comprehensive.html
`entry:Patient.request.method`: Why is it allowed to POST/PUT Patients in an ITI-65 transaction? Other `entry.request.method` are restricted.

**Comment by oliveregger** [comment]
The links to the MHD profile lead to v4.2.1 -> we don't use version specific links to ig's currently, this will always be the latest publish version
