### ISSUE TITLE
General comments

### ISSUE THREAD

**Issue by qligier** [ehealthsuisse/ch-epr-mhealth#76]
## http://fhir.ch/ig/ch-epr-mhealth/index.html
~The introduction is outdated.~

~What is the difference between 'Client authentication' and 'User Authentication'?~

~A reference to other MHD-like (FHIR/REST) transactions could be added. It seems like this profile is the main one for mobile transactions in the EPR (as its name implies), but it is not. A description could be added to explain that other transactions are described in e.g. PPQm, ATC.~ <ins>tracked in #140</ins>

## http://fhir.ch/ig/ch-epr-mhealth/sequencediagrams.html
query MPI_A-PID -> query MPI-PID and EPR-SPID

3rd diagram: [25] query documents -> [25] retrieve/access documents?

## http://fhir.ch/ig/ch-epr-mhealth/artifacts.html
Each profile uses its own artifact naming convention, it is hard to find something in this page. Can it be uniformized?

## Profiles
~They are all missing links to their transactions.~ <ins>already fixed</ins>

**Comment by oliveregger** [comment]
make the sequence diagram changes
