### ISSUE TITLE
Mobile Patient Demographics Query [ITI-78] (Alexander Kreutz from BFH)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-mhealth#80]
ch.fhir.ig.ch-epr-mhealth#3.0.0-ballot /iti-78.html

If the PDQ V3 response contains more than 5 matches or an error about too many matches there should be a message about more specific criteria required in the response and not just an empty response.

Example from PDQ V3 response:
  <ns1:detectedIssueEvent classCode="ALRT" moodCode="EVN">
            <ns1:code xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ns1:CD" code="ActAdministrativeDetectedIssueCode" codeSystem="2.16.840.1.113883.5.4"/>
            <ns1:triggerFor typeCode="TRIG">
              <ns1:actOrderRequired classCode="ACT" moodCode="RQO">
                <ns1:code code="LivingSubjectAdministrativeGenderRequested" codeSystem="2.16.756.5.30.1.127.3.10.2.1"/>
              </ns1:actOrderRequired>
            </ns1:triggerFor>
            <ns1:triggerFor typeCode="TRIG">
              <ns1:actOrderRequired classCode="ACT" moodCode="RQO">
                <ns1:code code="PatientAddressRequested" codeSystem="2.16.756.5.30.1.127.3.10.2.1"/>
              </ns1:actOrderRequired>
            </ns1:triggerFor>
            <ns1:triggerFor typeCode="TRIG">
              <ns1:actOrderRequired classCode="ACT" moodCode="RQO">
                <ns1:code code="BirthNameRequested" codeSystem="2.16.756.5.30.1.127.3.10.2.1"/>
              </ns1:actOrderRequired>
            </ns1:triggerFor>
          </ns1:detectedIssueEvent> 

Alexander Kreutz from BFH

**Comment by oliveregger** [comment]
see A5E1: 1.9.2.1.1 Special handling for more attributes requested
