### ISSUE TITLE
Home - Menu (Roeland Luykx (RALY GmbH))

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-epr-mhealth#83]
ch.fhir.ig.ch-epr-mhealth#3.0.0-ballot /

Perhaps the existing Menu "profiles" should be named "IHE Profiles" and an additional menu "profles" targeting to the overview of the defined resource profiles of the IG should be added like in other IG's.

Roeland Luykx (RALY GmbH)

**Comment by oliveregger** [comment]
IHE ITI Implementation Guides use in the menu 'Volume 1' for 'Profile' and 'Volume 2' for Transactions (Volume 4 would be for national extensions, but this not yet used in FHIR based profiles).

The CH EPR mHealth aggregates multiple profiles (this is also done in the IHE ITI Framwork), should we rename Profile and Transactions to 'Volume 1' and 'Volume 2' to be in sync with the I approach?

And then we can add the typical FHIR IG pages like 'Profile' etc.

**Comment by qligier** [comment]
Telco 10.01: Decision to keep Volume 1 & 2.
